theme: jekyll-theme-slate
title: Awrish Khan
description: My personal website created in order to better communicate and display personal projects, cetifications, etc.
background-image: url('/pictures/mountains.jpg')